version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: redis_cart
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  cart-service:
    build: .
    container_name: cart_service
    ports:
      - "3027:3027"
    depends_on:
      - redis
    environment:
      - PORT=3027
      - REDIS_HOST=redis:6379

volumes:
  redis_data:
