name: Deploy - Auth Service

on:
  push:
    branches:
      - main
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout backend
      uses: actions/checkout@v2

    - name: Configurar SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.AUTH_EC2_SSH_KEY }}

    - name: Preparar carpeta en EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.AUTH_EC2_HOST }} << 'EOF'
          sudo dnf update -y
          sudo dnf install docker -y
          sudo systemctl enable docker
          sudo systemctl start docker
          sudo usermod -aG docker ec2-user

          mkdir -p ~/auth-service
          cd ~/auth-service
          rm -rf *
        EOF

    - name: Subir código backend y .env
      run: |
        scp -o StrictHostKeyChecking=no -r ./autenticacion/auth-service/* ec2-user@${{ secrets.AUTH_EC2_HOST }}:~/auth-service/
        scp -o StrictHostKeyChecking=no ./autenticacion/auth-service/.env ec2-user@${{ secrets.AUTH_EC2_HOST }}:~/auth-service/.env

    - name: Construir y correr contenedor backend
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.AUTH_EC2_HOST }} << 'EOF'
          cd ~/auth-service
          docker stop auth-service || true && docker rm auth-service || true
          docker build -t auth-service .
          docker run -d -p 3001:3001 --name auth-service --env-file .env auth-service
        EOF
